### ISSUE TITLE
Process large amount of data from Wrangler on Jetstream

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#10]
I started an ECSS project with @ktyle, this is related to the other 2 "JupyterHub/Kubernetes/Jetstream" with @julienchastang and @rsignell-usgs.

In particular a part of this project is distributed data processing on Jetstream with dask. I plan on doing some benchmarks of distributed processing with Zarr files.

@ktyle do you have a suitable dataset for testing that I can use? also an example notebook would be useful.

Also, in the [January ECSS Symposium ](https://www.youtube.com/watch?v=gAtSCHqdZNk) (first half), Mats Rynge presented a project where they are mounting Wrangler file system on Jetstream directly, would that be an option to consider? @rsignell-usgs have you ever explored that option?

**Comment by julienchastang** [comment]
I've successfully NFS mounted a Wrangler file system on Jetstream with @jlf599. See:

https://github.com/Unidata/xsede-jetstream/blob/master/openstack/wrangler.md

**Comment by ktyle** [comment]
Yes, I too have NFS mounted Wrangler-based filesystems on Jetstream (and have been serving data there via @julienchastang 's containerized THREDDS for a while). I will be back in the office Thursday and will share a notebook or two that works with Zarr data that is in object store.
