### ISSUE TITLE
kubernetes/jupyterhub on jetstream for a GIS programing class

### ISSUE THREAD

**Issue by alvinhuff** [zonca/jupyterhub-deploy-kubernetes-jetstream#11]
Hello,
Thanks in advance for writing up the jupyterhub/jetstream guides!  I am attempting to help professor Susanna Werth at Arizona State University setup juypterhub/nbgrader for an online course she will be teaching in the fall.  Upfront I am nubie at this so I have been doing more reading than doing.  I followed your first guide using kubeadm on jetstream and made some progress with it, but I couldn't get rook to create the persistent volumes and then kubernetes would not start after I rebooted.  So I looked at your more recent guide kubespray/terraform, which at the same time seems simpler and more complex.  For virtual class room of 50+ students do you think kubeadm or kubespray would be more appropriate.    Is Kubernetes even necessary?  I got small VM to work on my mac after a few tries ubuntu 18 with The Littlest Jupyterhub, but of course that is just local.  I have not requested API access with Jetstream.  I have been looking for a Jetstream/Jupyterhub forum, but that doesn't seem to exist.  So I emailed the folks at jetstream to inquire if anyone else was trying to run Jupyterhub/Kubernetes and they pointed me back to you via github/issues.  I am totally willing to request jetstream api access if the kubeadm method is outdated.  I noticed you haven't updated that guide for awhile, but I don't want to "get in over my head ". I typically support physical classrooms and labs this my first foray into virtual teaching lab.  Any advice would be greatly appreciated.

cheers,

Alvin Huff

**Comment by zonca** [comment]
I think it depends on the memory each user needs, if they are not loading/generating large amount of data, probably just .5 GB RAM per user is enough, so if you get a `m1.xlarge` you should be fine. Also `nbgrader` is complicated to manage on a distributed system.
Then I would use The Littlest Jupyterhub, configure `nbgrader` and set memory limits accordingly: https://the-littlest-jupyterhub.readthedocs.io/en/latest/topic/tljh-config.html#tljh-set-user-limits

**Comment by alvinhuff** [comment]
Thanks for the advice!  Would it make sense then to create 2-4 vms and divide the students between them if they need more memory?  The allocation allows for 132 cpus and 360 gb of memory.

**Comment by zonca** [comment]
if it were not for `nbgrader`, yes. But if you are using `nbgrader` you want to have only 1 JupyterHub instance (maybe you can deploy nbgrader across multiple instances, please check the docs, but I'm sure has complications).
With a `xxlarge` you have 120GB, so you can give 2GB each, which should be enough for most students. 

If you need more and you need to go distributed, at that point Kubernetes is the most standard and supported option. But it is a huge step up in complexity, so if you can avoid it better.
