### ISSUE TITLE
how to install system packages?

### ISSUE THREAD

**Issue by rsignell-usgs** [zonca/jupyterhub-deploy-kubernetes-jetstream#2]
When I open an terminal in Jupyterhub, I find I don't have `vim` (or `nano` or `pico` for that matter).  Also no `curl`.

When I try:
```
sudo apt-get install vim
```
I get challenged for jovyan's password.   

Is this expected?

**Comment by zonca** [comment]
Yes sure, you are inside a container, you are not on the host machine.
Check the zero to jupyterhub docs on how to customize it.

Il ven 23 feb 2018, 13:46 Rich Signell <notifications@github.com> ha
scritto:

**Comment by rsignell-usgs** [comment]
Mi scusi, sto imparando JupyterHub lentemente!
