### ISSUE TITLE
bug in the ansible pinging script

### ISSUE THREAD

**Issue by davidedelvento** [zonca/jupyterhub-deploy-kubernetes-jetstream#20]
I am strictly following the directions of https://zonca.github.io/2019/02/kubernetes-jupyterhub-jetstream-kubespray.html and everything works until the ssh `ubuntu@$IP` see #19 

When running the ansible ping script I get this error (hiding the full IP addresses because I am paranoid). I guess there's a problem with escaping quotes:

```
ansible -i inventory/ddvento/hosts -m ping all
 [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

-k8s-master-1 | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"129.114.nn.nn\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
-k8s-node-nf-1 | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"10.0.0.4\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
-k8s-node-1 | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"129.114.nn.nn\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
-k8s-node-2 | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"129.114.nn.nn\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
```

If I ping these addresses by hand, everything works fine except one, which could be a second problem of this script or something else

The server on the private network behaves as follows:

```
ping 10.0.0.4
PING 10.0.0.4 (10.0.0.4) 56(84) bytes of data.
From 192.124.226.21 icmp_seq=1 Destination Net Unreachable
From 192.124.226.21 icmp_seq=3 Destination Net Unreachable
From 192.124.226.21 icmp_seq=4 Destination Net Unreachable
```

Now, if I go to https://tacc.jetstream-cloud.org/dashboard/project/instances/ I see that there is no Floating IP for this server, whereas there is for the others. If I try to ping the others on their private network IPs, I get the same Net Unreachable error

Is this a bug or am I doing anything wrong?

@vanderwb small progress, but not enough to make a dent

**Comment by zonca** [comment]
Only master has floating IP, please read through the Terraform / Kubespray docs.
