### ISSUE TITLE
Problem with install_jhub.sh

### ISSUE THREAD

**Issue by ktyle** [zonca/jupyterhub-deploy-kubernetes-jetstream#22]
Hi @zonca I am now running into an issue in https://zonca.github.io/2019/06/kubernetes-jupyterhub-jetstream-magnum.html at the step where I run bash install_jhub.sh .

The script fails with: 

Error: failed to download "jupyterhub/jupyterhub" (hint: running `helm repo update` may help)

I tried running that helm command; that succeeded with:

Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.

But re-running install_jhub.sh fails with the same error as before.

Thanks,

Kevin

**Comment by zonca** [comment]
were you able to install NGINX with helm?

**Comment by zonca** [comment]
possibly missing this:

    helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/

**Comment by ktyle** [comment]
Yes. I have since found the solution, which should be added to the documentation:

Prior to running install_jhub.sh, run the script 
  bash configure_helm_jupyterhub.sh

**Comment by zonca** [comment]
ok thanks
