### ISSUE TITLE
Simulate load on JupyterHub

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#23]
as per discussion with @julienchastang at Gateways 2019,
I will try `hubtraf`: https://github.com/yuvipanda/hubtraf

It would be nice especially to test autoscaling.

**Comment by julienchastang** [comment]
The "manual" test where we had a roomful of people (25) login went very well. At this point, it would indeed be preferable to have automatic load testing.

**Comment by julienchastang** [comment]
Are there any updates in this area? I would love to start doing more "automatic" load testing. Thanks!

**Comment by zonca** [comment]
next on my list!

**Comment by zonca** [comment]
@julienchastang Tutorial available at https://zonca.github.io/2019/10/loadtest-jupyterhub.html

Using this I also noticed some issues scaling down nodes, fixed those and updated the autoscaler tutorial and the configuration files in this repo. https://zonca.github.io/2019/09/kubernetes-jetstream-autoscaler.html

**Comment by julienchastang** [comment]
Thanks. I got this working for KubeSpray. It outputs a bunch of diagnostic messages. The question I have is what am I looking for in terms of success or failure? I tried scaling to 2 connections for a modestly sized cluster and things seemed to run OK. Then I scaled to 10 and resources were left dangling (e.g., "unclosed connection"). Maybe if I correctly size the cluster, I should see no failures.

**Comment by zonca** [comment]
@julienchastang I think you should check that all the hubtraf session starts with a reasonable delay and you don't see any errors.
what resources are dangling? can you paste some example logs?

**Comment by julienchastang** [comment]
I am getting consistent/expected results. In other words, scaling a cluster too small yields timeout errors, but adding nodes makes those errors go away. That is what is expected. Question: is there a limit to the number of nodes a cluster like this can handle/accept? Can you just keep adding worker nodes indefinitely? Is there a practical limit?

**Comment by zonca** [comment]
very good, thanks @julienchastang .
scaling up, I think that the bottleneck at some point could become the master node. But `data8` deploys zero-to-jupyterhub for >1000 users: https://data.berkeley.edu/news/data-8-thrives-and-campus.
So I think that running until a few hundreds of Jetstream nodes should not be a problem.
Let's check the different parts and reason if any could be an issue:
* Single user servers: no problem, as long as we have jetstream volumes for everyone we should be fine, they have always guaranteed resources.
* Hub: it is a single point of failure, as for load under scale, we should make sure it has enough CPU and RAM to handle proxying, so we could check if under load it uses too much of its share and we can increase it via `kubectl`.
* Master node: this is the weakest point of the deployment, which is not a problem just at scale, but it is a significant issue for **reliability**. Unfortunately Jetstream doesn't provide Openstack Load Balancers. Ideally we should have a group of load-balancers that proxy traffic to multiple master nodes. So that if the master node with the hub dies, the hub container is immediately created again on the second master node mounting the data volumes and starting so again.
* Kubernetes: this deployment doesn't use a lot of Kubernetes resources, so I don't think there is any issue
* Openstack: ~100 VMs and ~1000 small volumes I don't think are problematic

**Comment by julienchastang** [comment]
@zonca. I am obtaining interesting experimental results. See the tables below. The data reveal that I can accommodate the same number of users whether I am on a cluster of XL VMs or medium VMs. Roughly, 5 users per node (look for the rows with zero timeouts and unclosed connections). I have no idea why that is, I am simply reporting the data. I suspect that server-start timeout errors are related to volume creation and attachment though that is just speculation. I don't know why that would be related to the size of the VM. I have not tried obtaining results for VMs beyond XL or medium. The only downside I can think of is that we will have to create clusters with more VMs to accommodate more users (4 to 1 cpu ratio between XL and medium).

ping @jlf599

**XL VM worker node experiment** XL VM: 24 cpu, 60 gb ram

| nodes | hubtraf 'users' | users/node | server-start timeouts | unclosed connections |
|----- |--------------- |---------- |--------------------- |-------------------- |
| 3     | 10              | 3.3        | 0                     | 0                    |
| 3     | 30              | 10         | 12                    | 6                    |
| 6     | 30              | 5          | 0                     | 0                    |
| 6     | 40              | 6.7        | 3                     | 3                    |

**medium VM worker node experiment** medium VM: 6 cpu, 16 gb ram

| nodes | hubtraf 'users' | users/node | server-start timeouts | unclosed connections |
|----- |--------------- |---------- |--------------------- |-------------------- |
| 6     | 30              | 5          | 0                     | 0                    |
| 6     | 40              | 6.7        | 6                     | 4                    |
| 12    | 40              | 3.33       | 0                     | 0                    |
| 12    | 60              | 5          | 0                     | 0                    |
| 12    | 70              | 5.8        | 4                     | 4                    |

And here is the `secrets.yaml` file I am working with for this JupyterHub, just as an FYI. Volume storage capacity, memory and CPU may be of interest.

```yaml
hub:
  cookieSecret: "xxx"

proxy:
  secretToken: "xxx"

ingress:
  enabled: true
  hosts:
    -  js-X-Y.jetstream-cloud.org

auth:
  type: dummy
  admin:
    users:
      - admin

singleuser:
  storage:
    capacity: 1Gi
  memory:
    guarantee: 2G
    limit: 2G
  cpu:
    guarantee: 1 
    limit: 1 
  image:
    name: unidata/pyaos-ams-2020
    tag: 398a5bc42d03
  lifecycleHooks:
    postStart:
      exec:
          command:
            - "sh"
            - "-c"
            - >
              gitpuller https://github.com/julienchastang/pyaos-ams-2020 master pyaos-ams-2020;
```

**Comment by zonca** [comment]
I think we need to drill down on the timeouts and understand where they are coming from. can you look at the kubernetes logs after the fact and understand what is going on?

I am about to deploy another production system, and I will run these tests myself sometime in January.

**Comment by julienchastang** [comment]
See both client-side hubtraf logs(`hubtraf.log`) and server-side kubectl logs (`kubectl-logs-hub.log`)

https://gist.github.com/julienchastang/a1d07209bde4060931369e383a69cb7e

This is a 2 node cluster (not including master -- that applies to earlier results, as well) of medium size VMs with 15 users trying to connect. According to earlier data, I expect this to fail, since there are 7.5 users/node. I showed before that errors disappear at 5 users/node.

**Comment by zonca** [comment]
* for a medium VM 5 users/node are expected: we have 6 CPUs and we are requesting 1 CPU/user.
* for XL VM we expect at least to be able to support 10 users/node, in theory even 20 users/node

**Comment by zonca** [comment]
@julienchastang to check if it is the volumes, can you re-run with no storage? https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/blob/master/config_no_storage.yaml

**Comment by julienchastang** [comment]
Yep, no storage makes a big difference:

**XL VM worker node experiment, NO storage volumes** XL VM: 24 cpu, 60 gb ram

**XL VM worker node experiment, NO storage volumes** XL VM: 24 cpu, 60 gb ram

| nodes | hubtraf 'users' | users/node | server-start timeouts | unclosed connections |
|----- |--------------- |---------- |--------------------- |-------------------- |
| 2     | 10              | 5          | 0                     | 0                    |
| 2     | 20              | 10         | 0                     | 0                    |
| 2     | 40              | 20         | 0                     | 0                    |
| 10    | 100             | 10         | 0                     | 0                    |
| 10    | 200             | 20         | 0                     | 0                    |

Moreover, everything is way snappier with ""no storage"; tests and and my own experimentation.

This result has me thinking...

We are about to host a 90 minute Python workshop with ~200 users at AMS 2020. I want the  students to have a smooth, successful experience during the workshop, but I don't care what happens to their work after the workshop is over. (We can have them download the material they care about onto their local laptops, if they want.) Question: Is there any reason not to use the "no storage" solution for this workshop? (ping @lesserwhirls) All their work will reside in memory, but that seems fine for a short workshop. If the server blows up, we will have more pressing concerns than recovering the users' work. In addition, I believe this solution will be more reliable.

**Comment by zonca** [comment]
@julienchastang yes, for 90 minutes I don't think you need persistent storage.
Also consider that the user container persists for a while in Kubernetes, so users data are not purged immediately. If you tweak culling so that users containers are not wiped out, you can have users be able to recover they data even a few days after the workshop, then you can tear down all of it.

**Comment by julienchastang** [comment]
@zonca Given this, do you have an opinion on a configuration that has a smaller number of larger VMs (XL) or a larger number of smaller VMs (medium). I am leaning towards the latter.

**Comment by zonca** [comment]
> @zonca Given this, do you have an opinion on a configuration that has a smaller number of larger VMs (XL) or a larger number of smaller VMs (medium). I am leaning towards the latter.

I have a small preference for larger VMs because I feel that powerful machines running many containers have capability of balancing load across them, and second you are stressing less the Jetstream API using less machines. But they are secondary factors.

**Comment by zonca** [comment]
@julienchastang @pibion I also see delays attaching volumes:

```
  Type     Reason                  Age                  From                                     Message
  ----     ------                  ----                 ----                                     -------
  Normal   Scheduled               4m39s                default-scheduler                        Successfully assigned jhub/jupyter-nebula-2esdsc-2eedu-2d14 to k8s-cdms-vevrigyiugsy-master-0
  Warning  FailedAttachVolume      26s (x4 over 3m37s)  attachdetach-controller                  AttachVolume.Attach failed for volume "pvc-84597050-21cc-11ea-a8d7-fa163e668c4e" : Volume "9ba20f00-c804-454b-a1c0-958b3b8ea9d5" failed to be attached within the alloted time
  Warning  FailedMount             20s (x2 over 2m35s)  kubelet, k8s-cdms-vevrigyiugsy-master-0  Unable to mount volumes for pod "jupyter-nebula-2esdsc-2eedu-2d14_jhub(3933b969-21cf-11ea-a8d7-fa163e668c4e)": timeout expired waiting for volumes to attach or mount for pod "jhub"/"jupyter-nebula-2esdsc-2eedu-2d14". list of unmounted volumes=[volume-nebula-2esdsc-2eedu-2d14]. list of unattached volumes=[volume-nebula-2esdsc-2eedu-2d14]
  Normal   SuccessfulAttachVolume  18s                  attachdetach-controller                  AttachVolume.Attach succeeded for volume "pvc-84597050-21cc-11ea-a8d7-fa163e668c4e"      
```

```
  Type     Reason                  Age    From                                     Message                                           
  ----     ------                  ----   ----                                     -------
  Normal   Scheduled               3m52s  default-scheduler                        Successfully assigned jhub/jupyter-nebula-2esdsc-2
eedu-2d8 to k8s-cdms-vevrigyiugsy-minion-1
  Normal   SuccessfulAttachVolume  3m48s  attachdetach-controller                  AttachVolume.Attach succeeded for volume "pvc-9460
b7d0-21cc-11ea-a8d7-fa163e668c4e"
  Warning  FailedMount             109s   kubelet, k8s-cdms-vevrigyiugsy-minion-1  Unable to mount volumes for pod "jupyter-nebula-2esdsc-2eedu-2d8_jhub(368d2cf7-21cf-11ea-a8d7-fa163e668c4e)": timeout expired waiting for volumes to attach or mount for pod "jhub"/"ju
pyter-nebula-2esdsc-2eedu-2d8". list of unmounted volumes=[volume-nebula-2esdsc-2eedu-2d8]. list of unattached volumes=[volume-nebula-2esdsc-2eedu-2d8]                                                                                                                     Normal   Pulled                  92s    kubelet, k8s-cdms-vevrigyiugsy-minion-1  Container image "jupyterhub/k8s-network-tools:0.8.
2" already present on machine                                                                                                        
  Normal   Created                 91s    kubelet, k8s-cdms-vevrigyiugsy-minion-1  Created container               
```
Opened XSEDE ticket

anyway in my testing all the containers eventually started successfully, I didn't encounter any permanent error. There is a timeout of 5 minutes in the hub that is causing errors, but a user could wait 6 or 7 minutes and have the session start.
Workaround is to increase that timeout, see https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/commit/a0f29fa4409c27e2b762291e8183abc62072633b

So let's see if the Jetstream can do anything to improve, otherwise we will live with this.

**Comment by julienchastang** [comment]
I've updated the "NO Volume" table above for 100 and 200 users and 10 XL nodes. I am not seeing any timeout or unclosed connection errors. However, for 200 users, I am seeing "429 Too Many Requests". Not sure if this is a problem. Via the admin console, I can see 200 users so things seem good there.

**Comment by zonca** [comment]
copy of the email sent to XSEDE:

I tested today, I have only 11 users connecting randomly over a time span of 3 minutes.
10 volumes were created very quickly and users pods started within a couple of minutes.
However 1 got stuck, see the log from kubernetes:

```
Events:                                                                                                                                Type     Reason                  Age                     From                                     Message                          
  ----     ------                  ----                    ----                                     -------                          
  Normal   FailedScheduling        6m44s (x25 over 6m44s)  default-scheduler                        Volume binding started, waiting for completion                                                                                                                          Warning  FailedMount             2m26s (x2 over 4m40s)   kubelet, k8s-cdms-pk42kfcjuvt6-minion-1  Unable to mount volumes for pod "jupyter-nebula-2esdsc-2eedu-2d0_jhub(372860e8-30b1-11ea-9cf9-fa163e3a64de)": timeout expired waiting for volumes to attach or mount for pod "jhub"/"jupyter-nebula-2esdsc-2eedu-2d0". list of unmounted volumes=[volume-nebula-2esdsc-2eedu-2d0]. list of unattached volumes=[volume-nebula-2esdsc-2eedu-2d0]                                                                                                  
  Warning  FailedAttachVolume      85s (x5 over 5m41s)     attachdetach-controller                  AttachVolume.Attach failed for volume "pvc-37262d7d-30b1-11ea-9cf9-fa163e3a64de" : Volume "e3d62c15-88cf-4ba0-8871-4950b8e8e3cc" failed to be attached within the alloted time
  Normal   SuccessfulAttachVolume  73s                     attachdetach-controller                  AttachVolume.Attach succeeded for volume "pvc-37262d7d-30b1-11ea-9cf9-fa163e3a64de"
  Normal   Pulled                  25s                     kubelet, k8s-cdms-pk42kfcjuvt6-minion-1  Container image "jupyterhub/k8s-network-tools:0.8.2" already present on machine
  Normal   Created                 21s                     kubelet, k8s-cdms-pk42kfcjuvt6-minion-1  Created container
  Normal   Started                 20s                     kubelet, k8s-cdms-pk42kfcjuvt6-minion-1  Started container
  Normal   Pulled                  20s                     kubelet, k8s-cdms-pk42kfcjuvt6-minion-1  Container image "jupyterhub/k8s-singleuser-sample:0.8.2" already present on machine
  Normal   Created                 18s                     kubelet, k8s-cdms-pk42kfcjuvt6-minion-1  Created container                
  Normal   Started                 18s                     kubelet, k8s-cdms-pk42kfcjuvt6-minion-1  Started container
```

So it took almost 6 minutes to attach the volume. I checked the openstack volume `e3d62c15-88cf-4ba0-8871-4950b8e8e3cc` during this delay checking for errors but didn’t find any, the volume was in “available” state.

**Comment by zonca** [comment]
ok, the Jetstream team identified the problem and fixed the issue pushing a new version of `libvrt`. Now I see no volumes stuck. Additional testing is very welcome.
