### ISSUE TITLE
ansible-playbook issue

### ISSUE THREAD

**Issue by pibion** [zonca/jupyterhub-deploy-kubernetes-jetstream#24]
In the "Install Kubernetes with kubespray" section of https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray.html, I'm running into a persistent error when I try to run the playbook.

I've attached the output I get when running `ansible-playbook --become -i inventory/$CLUSTER/hosts cluster.yml` - I always seem to get an error on

```
TASK [bootstrap-os : Assign inventory name to unconfigured hostnames (non-CoreOS and Tumbleweed)]
```

I'm not sure if it's related, but I don't seem to have the file `inventory/$CLUSTER/group_vars/all.yml`.  I do have an `inventory/$CLUSTER/group_vars/all/all.yml` but this file doesn't have the string "bootstrap_os".

[playbook_out.txt](https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/files/3849118/playbook_out.txt)

**Comment by zonca** [comment]
There are some variables missing in your environment. cross-check all the steps in the tutorial in make sure all of them are defined.
You see that the name of the two machines created starts with -.
They should have your username before that.

**Comment by pibion** [comment]
Argh, apologies, this step runs (eventually) when I have $CLUSTER defined as described in the instructions.

I'm now running into issues with some of the kubectl commands, but in the meantime I've been able to successfully follow the instructions for deploying with magnum (https://zonca.github.io/2019/06/kubernetes-jupyterhub-jetstream-magnum.html).

If it's helpful I'm happy to keep pestering you with issues while following the kubernetes tutorial but if not we'll just use magnum instead.

**Comment by zonca** [comment]
Magnum is better currently, see also the follow-up totorial on autoscaler
