### ISSUE TITLE
jetstream_kubespray (terraform/ansible)

### ISSUE THREAD

**Issue by glass-ships** [zonca/jupyterhub-deploy-kubernetes-jetstream#26]
```
jetstream_kubespray: v2.8.2
openstack v: 4.0.0
ansible v: 2.7.15
image: "JS-API-Featured-Ubuntu18-Sep-10-2019"
```
Following the instructions [here](https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray.html) I'm able to go all the way through creating the virtual machine and `ansible-playbook` command. 

However, when I try to `ssh` into the image I notice a few things:
1. The image is named `-k8s-node-fs-1` as the $CLUSTER variable is not defined at any point previous, and is not included in the name during node creation. 

2. Upon accessing the image, user is instructed to reboot (not exactly viable in ephemeral containers) 

and 3. `kubectl` itself is not installed within the image. 

Is it required for the user to install `kubectl` after sshing into the image? My suspicion is the k8s configuration within the image either will not persist or does not yet exist.

**Comment by zonca** [comment]
1)

    export CLUSTER=$USER

should be defined just before running terraform. See the `Run Terraform` section on the tutorial. Better run `terraform_destroy.sh`, define that variable and rerun terraform again.

2) no need to reboot, the VM image used was recently updated, it is pretty secure already. Anyway, if you reboot the machine, kubernetes should come back up with all the containers.

3) `kubectl` must be installed, please check carefully in the logs of ansible, some step is possibly failing. Anyway before worrying about this, make sure step 1) is fixed.

**Comment by glass-ships** [comment]
Thanks, Zonca. I do see that command now, and have set CLUSTER to $USER. 

I then source openrc, terraform init and apply. 

Then, I install ansible via the `requirements.txt`, and run the `ssh-add` and `ansible` commands listed. 

Everything runs as expected/described in your guide to this point, but `ansible become` succeeds with some errors. I've attached the output of this command, perhaps you will be able to make some sense of it. 

Upon `ssh ubuntu@$IP`, i again get: 
```bash 
$ kubectl get pods

Command 'kubectl' not found, but can be installed with:

sudo snap install kubectl
```
[ansible-output.txt](https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/files/3883003/ansible-output.txt)

**Comment by zonca** [comment]
it fails installing packages.
when the VM is created it automatically starts a `apt upgrade`, this locks APT and ansible cannot install what is needed for kubernetes.
after you create with terraform, wait 20 min and then run ansible,
there should be **no failed ansible tasks**, if there is, rerun ansible until you get no failed tasks.

**Comment by zonca** [comment]
no feedback
