### ISSUE TITLE
Investigate autoscaling with Kubespray again

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#34]
Check if we can use the Cluster Autoscaler to launch a general script which uses Kubespray to add or remove instances

**Comment by zonca** [comment]
unfortunately that functionality in Cluster Autoscaler that allowed the autoscaler to interface with a generic REST API endpoint to create and delete nodes is not planned to be added back in.
They are discussing about an alternative to that using remote procedure calls `gRPC`, see this proposal:

https://github.com/kubernetes/autoscaler/pull/3140

I am monitoring that and if there are news we can revisit.
But as of now, no way to do autoscaling with the kubespray based deployment.

**Comment by zonca** [comment]
checked again, the custom cloud provider mentioned above is still work in progress, so we don't have a way of supporting cluster autoscaler in a kubespray deployment.

**Comment by zonca** [comment]
there is recent developments in the implementation of the custom autoscaler I linked above, but it is not ready yet. I don't want to spend too much time trying to build from source, I prefer to wait.

**Comment by zonca** [comment]
well, moreover that is just a "proposal" for a custom cloud provider, once that is accepted and merged into the project, they will start actually implementing it, so it is still far away.

**Comment by zonca** [comment]
it looks like Kubespray support in the Cluster Autoscaler is very far away, so I decided to implement a simple script myself to do the autoscaling, see tutorial at https://zonca.dev/2021/01/autoscaling_script_kubespray_jupyterhub.html

@julienchastang do you have any interest on testing this out or you are happy with manual scaling?

**Comment by zonca** [comment]
will test autoscaling in production in the future, for now it has only been for exploration purposes.

**Comment by julienchastang** [comment]
I missed the "@" mention earlier. Sorry about that.
