### ISSUE TITLE
Create new tutorial for shared volume with NFS server

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#35]
As part of this tutorial https://zonca.dev/2020/02/cvmfs-kubernetes.html
I created a NFS server image, which however also includes a CVMFS server.

It would be nice to factor out just the NFS server in new image and do a new tutorial.

Let's do 1 read-only folder and 1 read-write folder.

/cc @julienchastang

**Comment by zonca** [comment]
@julienchastang here it is:

https://zonca.dev/2020/07/nfs-server-kubernetes-jetstream.html

it is a bit restrictive on permissions, it's either read-only or everyone-writes, no per-user files.
Do you think this is suitable for you? Otherwise let's discuss here.

**Comment by julienchastang** [comment]
Thank you! I am taking a bit of vacation this week, but I will try to test this out soon.
