### ISSUE TITLE
Plan for December 2020

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#42]
@julienchastang and @pibion, you are the PIs of my 2 ECSS consultations (both JupyterHub on Kubernetes on Jetstream).

I have extra funding on XSEDE in December, so I'd like to dedicate time to some foundational work, not specific to any project.

Here are the 2 main options:

* Update the version of `kubespray`, I last updated in June, I'm using Kubespray 2.13.1, which deploys Kubernetes 1.17.6 (initially released in Dec 2019). The last version of Kubespray would deploy Kubernetes 1.18.10, see [release announcement](https://kubernetes.io/blog/2020/03/25/kubernetes-1-18-release-announcement/). @julienchastang any issue with `kubespray` itself or with Kubernetes 1.17 that could benefit from an upgrade?
* on Magnum, I don't control the version of Magnum (that is handled by the Jetstream team), but I can make sure the Autoscaler still works, see https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/issues/31

**Comment by pibion** [comment]
@zonca this is exciting news!

Autoscaling is something important for the SuperCDMS JupyterHub in terms of conserving resources, but I don't have enough technical knowledge about either to weigh in strongly, so I'm mainly here to say I trust your judgement.

**Comment by julienchastang** [comment]
Yes, great news indeed. I am a heavy user of kubespray so seeing that maintained is always positive. Thank you again.

**Comment by zonca** [comment]
ok, good thanks,
as there are no specific issues on the Kubespray deployment and the current release is still quite recent, let's do that last

So the plan is:
* Autoscaler on Magnum (#31)
* Check if there is any change in the Autoscaler support for `kubespray`, #34 
* Then I'll update `kubespray` (by the time I'll get to this `kubespray` will probably have released another version)

**Comment by zonca** [comment]
December slipped away too quickly... will proceed ahead on these in January

**Comment by zonca** [comment]
tried to deploy a cluster with Magnum, using my latest tutorial, https://zonca.dev/2020/05/kubernetes-jupyterhub-jetstream-magnum.html, it is not working anymore, it gets stuck in building the cluster.
I don't want to get into a debugging hole.
I have the impression that we could have an autoscaler that works with kubespray in the next few weeks.
If that is the case, there is no reason to use the Magnum deployment strategy anymore.
So for the time being I'll update `kubespray` (3rd item I mentioned above), then as soon as they have a first release of the `autoscaler` for `kubespray` I'll focus on that.

**Comment by zonca** [comment]
last `kubespray` release is from October, they are about to release a new version, 2.15, I prefer to wait for that release and then upgrade directly to 2.15:

https://github.com/kubernetes-sigs/kubespray/issues/7069

**Comment by zonca** [comment]
ok,
so I implemented #44 and an autoscaling script for kubespray: https://zonca.dev/2021/01/autoscaling_script_kubespray_jupyterhub.html

I am going to let Magnum go for the time being, waiting for the summer when Jetstream 2 comes online, and hoping they provide more support to have Magnum working consistently.

**Comment by pibion** [comment]
@zonca I think this is very reasonable, especially given the timescale that autoscaling would be nice for.

I'm hoping to get two steady analyzers on the XSEDE platform over the course of this semester.  I suspect we'll have some spikes later in the spring and maybe in the summer as well, we're planning on running an analysis workshop.  Previously, about 2 to 4 people have used XSEDE during these.

I think it will be Fall 2021 before we have heavier workshop use - I'm expecting this to come from workshops that have people outside CDMS.
