### ISSUE TITLE
Update kubespray to 2.15.0

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#44]
Kubespray 2.15.0 was released in mid-January 2021, started to work on adapting it to Jetstream, I will then either update the last tutorial (was based on 2.13.1) or write a new one, depending on how different it comes out.

**Comment by zonca** [comment]
this is part of #42

**Comment by zonca** [comment]
Ignored error by ansible:

```

TASK [kubernetes/node : Modprobe nf_conntrack_ipv4] ***********************************************************
fatal: [kubejetstream-k8s-node-1]: FAILED! => {"changed": false, "msg": "modprobe: FATAL: Module nf_conntrack_i
pv4 not found in directory /lib/modules/5.4.0-52-generic\n", "name": "nf_conntrack_ipv4", "params": "", "rc": 1
, "state": "present", "stderr": "modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/modules/
5.4.0-52-generic\n", "stderr_lines": ["modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/mo
dules/5.4.0-52-generic"], "stdout": "", "stdout_lines": []}
...ignoring
fatal: [kubejetstream-k8s-master-1]: FAILED! => {"changed": false, "msg": "modprobe: FATAL: Module nf_conntrack
_ipv4 not found in directory /lib/modules/5.4.0-52-generic\n", "name": "nf_conntrack_ipv4", "params": "", "rc":
 1, "state": "present", "stderr": "modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/module
s/5.4.0-52-generic\n", "stderr_lines": ["modprobe: FATAL: Module nf_conntrack_ipv4 not found in directory /lib/
modules/5.4.0-52-generic"], "stdout": "", "stdout_lines": []}
...ignoring
```

**Comment by zonca** [comment]
@julienchastang I have the new version working, it installs Kubernetes 1.19 and JupyterHub-Helm 0.11.1

It is simplified in a few points compared to the last version, so I feel it is more robust, but needs testing when you have time!

https://zonca.dev/2021/01/kubernetes-jetstream-kubespray.html

**Comment by zonca** [comment]
ok, I also updated the tutorial on `cert-manager` https://github.com/zonca/zonca-blog/commit/cb4f2828a6eb591f4717240fcdcdf9e4acddf55c, https://zonca.dev/2020/03/setup-https-kubernetes-letsencrypt.html

**Comment by rptaylor** [comment]
The ignored error is related to a workaround for the nf_conntrack_ipv4 module name changing in RHEL8.3:
https://github.com/kubernetes-sigs/kubespray/pull/6988

**Comment by julienchastang** [comment]
Great! I will give this a shot soon. (The biggest problem for me all along has been volume attachment problems. I now solve that by disabling culling so the server is always available with disk attached.)

**Comment by zonca** [comment]
@julienchastang have you had a chance to test kubespray 2.15?
I had the impression that startup of user containers is faster, it seems like volume attachment is quicker, now I am not sure this is the new Kubernetes version or an improvement on Jetstream.

**Comment by julienchastang** [comment]
Sorry, I forgot about this. I deployed some clusters for the spring semester back in Dec/Jan, and then did not get back to this. I have a grant due in a few days, and then I'll return to this work.

**Comment by julienchastang** [comment]
Sorry for the very long delay :-( I am finally getting around to looking at this. First issue I see is that I think:

`~/.ssh/zonca-api-key.pub`

should be

`~/.ssh/id_rsa.pub`

**Comment by julienchastang** [comment]
Also, I believe names are not being parameterized, e.g., everything is named with `kubejetstream` like `kubejetstream-router` instead of being parametrized with the `CLUSTER` name e.g., `ou2020fall` resulting in `ou2020fall-router`. Maybe an env variable has changed somewhere?

*EDIT* : OK, I see, the cluster name is now parameterized in `cluster.tfvars`. I think disregard this comment.

**Comment by julienchastang** [comment]
OK, I have a zero to jupyterhub server running after following these instructions. Basically, everything worked [as documented](https://zonca.dev/2021/01/kubernetes-jetstream-kubespray.html). I may have some minor follow-up comments later in the week.

**Comment by zonca** [comment]
thanks @julienchastang for the feedback!
I am now getting both the cluster and network name from the CLUSTER variable: https://github.com/zonca/jetstream_kubespray/commit/588aab0164efdd95c46f840a2ee2c6440f340c06
I tested it and it works as expected.

**Comment by zonca** [comment]
ok, I consider this completed, any other problem or feedback you find, please open a new issue!
