### ISSUE TITLE
Update dask gateway tutorial

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#47]
Need to update the tutorial from Aug 2020:

https://zonca.dev/2020/08/dask-gateway-jupyterhub.html

Trying with dask gateway 0.9.0, hitting a routing issue:

https://dask.discourse.group/t/deploy-dask-gateway-on-kubernetes-as-a-jupyterhub-service/200

@julienchastang, will notify you when it's ready.

**Comment by zonca** [comment]
@julienchastang here is the new tutorial:

https://zonca.dev/2022/01/dask-gateway-jupyterhub.html

however I suggest to wait for the next release of dask gateway, it should be close, see https://github.com/dask/dask-gateway/issues/381, so you can use a newer `dask` version.

I plan to update the tutorial as soon as it comes out, and I'll update this issue.

**Comment by julienchastang** [comment]
Excellent. I look forward to trying this out.

**Comment by julienchastang** [comment]
Thanks @zonca. I am not quite clear on the section that concerns the version of the Dask gateway. When I do a `help('modules')`, I don't see dask anywhere in the root environment though I may be looking in the wrong place. Moreover, I see in `dask_gateway/config_jupyterhub.yaml`, the ` pangeo/base-notebook` environment listed, but how do I access that from the Hub? I don't see it in the list of kernels. Lastly, how do I determine the version of Dask I am using, and how do I downgrade the version?  Thanks again.

**Comment by julienchastang** [comment]
I also added your username to the allowlist on https://js-157-85.jetstream-cloud.org/. There is a kernel called `rut-spring-2022` that has dask [0] installed. However, when I invoke `cluster = gateway.new_cluster()`, I get `ValueError: Cluster jhub.028ef14046f4468486734eaae84ecf62 not found`.  The previous step about checking cluster status seems to work OK.

[0] https://github.com/julienchastang/jupyter-classroom/blob/master/rut-spring-2022/environment.yml
`

**Comment by zonca** [comment]
> Thanks @zonca. I am not quite clear on the section that concerns the version of the Dask gateway. When I do a `help('modules')`, I don't see dask anywhere in the root environment though I may be looking in the wrong place. Moreover, I see in `dask_gateway/config_jupyterhub.yaml`, the ` pangeo/base-notebook` environment listed, but how do I access that from the Hub? I don't see it in the list of kernels. Lastly, how do I determine the version of Dask I am using, and how do I downgrade the version? Thanks again.

if you use `base-notebook` there is only 1 kernel, I think named "Python 3", which has `dask` and `dask-gateway` installed.
You can just `pip install` the right version right from the Single user server. But of course better is to use an environment already with the right dask version.

**Comment by zonca** [comment]
> I also added your username to the allowlist on https://js-157-85.jetstream-cloud.org/. There is a kernel called `rut-spring-2022` that has dask [0] installed. However, when I invoke `cluster = gateway.new_cluster()`, I get `ValueError: Cluster jhub.028ef14046f4468486734eaae84ecf62 not found`. The previous step about checking cluster status seems to work OK.
> 
> [0] https://github.com/julienchastang/jupyter-classroom/blob/master/rut-spring-2022/environment.yml `

I managed to connect, I see `dask` 2.21.0 and `dask-gateway` 0.8.0.

I created a PR with the same configuration that I am using: https://github.com/julienchastang/jupyter-classroom/pull/1

**Comment by julienchastang** [comment]
Thanks @zonca. Were you then able to create a cluster? At any rate, I created and installed the environment, but I can no longer see the kernel `rut-spring-2022` in the list of available kernels. This is similar to experiences I have had in the past when trying to install and run Dask on Jetstream.

**Comment by zonca** [comment]
I think that it would be easier to just install everything in the base environment or do you need separate kernels for some other reason?

Sorry, I didn't think about trying to run a cluster, I can try in a few hours.

**Comment by julienchastang** [comment]
Is the base environment `pangeo/base-notebook:2020.07.28` referenced in `dask_gateway/config_jupyterhub.yaml`? I'm trying to figure out how to build the Docker container: https://github.com/julienchastang/jupyter-classroom/blob/master/rut-spring-2022/Dockerfile and specifically what base container I should use.

**Comment by zonca** [comment]
In principle The only requirement that you have inside your single user environment is to have the three packages installed. The ones that I added to the pull request. You can use any base image you want.
Just with those you should be able to connect to dask gateway.
What happens if you try now? Which error do you get?

Another thing you could try is for testing purposes to use the same Jupiter hub configuration that I am using in my tutorial. So that we can make sure that the rest of the dask gateway setup is working properly.

**Comment by zonca** [comment]
About your earlier question, Yes correct. That is the container that I am using for testing.

**Comment by julienchastang** [comment]
> Another thing you could try is for testing purposes to use the same Jupiter hub configuration that I am using in my tutorial.

I think that is what I am doing (inadvertently).  `dask_gateway/config_jupyterhub.yaml` supersedes or takes precedence over `secrets.yaml` -- is that correct? (Edit: That would explain why I am not seeing the environment I specified in `secrets.yaml`)

**Comment by zonca** [comment]
I'm not sure. I think it depends on the order. You give it on the command line

**Comment by julienchastang** [comment]
FYI this is what is installed in the `pangeo/base-notebook:2020.07.28` `notebook` conda environment by default.

```
dask                      2.21.0                     py_0    conda-forge
dask-core                 2.21.0                     py_0    conda-forge
dask-gateway              0.8.0            py37hc8dfbb8_0    conda-forge
dask-kubernetes           0.10.1                     py_0    conda-forge
dask-labextension         2.0.2                      py_0    conda-forge
pangeo-dask               2020.07.27                    0    conda-forge
distributed               2.21.0           py37hc8dfbb8_0    conda-forge
```

Are these versions acceptable or do we definitely need: 

```
dask=2.30.0
distributed=2.30.0
dask-gateway=0.9.0
```

The reason I ask is I have been having a difficult time updating these packages with the conda satisfiability solvers basically failing.

**Comment by zonca** [comment]
No, you cannot use those versions
Why don't you pip install inside the conda environment? I know it's not the
cleanest but generally works fine

**Comment by julienchastang** [comment]
After much trial and error, this is the docker command that finally worked:

```
RUN . /srv/conda/etc/profile.d/conda.sh && conda activate notebook && \
    pip install 'dask==2.30.0'  && \
    pip install 'distributed==2.30.0'  && \
    pip install 'dask-gateway==0.9.0'
```

Note the invocation of `conda.sh` to activate the environment. That is required.

But I still have:

```
(notebook) jovyan@jupyter-julienchastang:~$ pip list | grep -i dask
dask                          2.21.0
dask-gateway                  0.8.0
dask-kubernetes               0.10.1
dask-labextension             2.0.2
(notebook) jovyan@jupyter-julienchastang:~$ pip list | grep -i dist
distributed                   2.21.0
```

As a next step, I may try to build my own Pangeo environment with required version of the libraries (rather than inheriting from `pangeo/base-notebook:2020.07.28`). I don't have any better ideas.

**Comment by zonca** [comment]
I see that you are doing Conda activate notebook, So you have two environments, the base environment and the notebook environment.
I recommend instead to use only one

**Comment by zonca** [comment]
Also maybe pip is not installed inside the condo environment? So it's picking up pip from some other location in the path?

**Comment by julienchastang** [comment]
There is something weird going on. In particular, the Docker image that I am specifying in `secrets.yaml` is not deploying correctly and is not to be found anywhere. 

```
  image:
    name: unidata/rut-spring-2022
    tag: be53538c1cdd
```


That explains what we have been seeing in this thread for the last few messages. As a sanity check, I installed `metpy` in the container:

```
RUN . /srv/conda/etc/profile.d/conda.sh && conda activate notebook && \
    conda install pip  && \
    pip install 'dask==2.30.0'  && \
    pip install 'distributed==2.30.0'  && \
    pip install 'metpy'  && \
    pip install 'dask-gateway==0.9.0'
```

  yet, `metpy` is nowhere to be found anywhere in any kernel in the JupyterHub.

Should I be using `dask_gateway/config_jupyterhub.yaml` instead to specify the Docker image?

**Comment by julienchastang** [comment]
I also tried to change the image in `dask_gateway/config_jupyterhub.yaml` but to no effect. I think things are stuck as far as I can tell.

**Comment by zonca** [comment]
For debugging purposes, you could merge everything into one single YAML file

**Comment by julienchastang** [comment]
OK, one mystery solved: During redeployment you have to call *both* `install_dask-gateway.sh ` and `install_jhub.sh`. Maybe that is implied, but I missed it. Also note that dask `0.8.0` is referenced:

```
You've installed Dask-Gateway version 0.8.0, from chart
```

but we are still expected to go with version `0.9.0`. Is that correct?

**Comment by julienchastang** [comment]
After that, when trying to launch a cluster I get:

```
GatewayClusterError: Cluster 'jhub.c784abd15c3b40e9afa261110626af74' failed to start, see logs for more information
```

which are possibly related to TimeOut errors according to the logs.

**Comment by zonca** [comment]
can you check that your "install dask gateway" script specifies 0.9.0? https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/blob/master/dask_gateway/install_dask-gateway.sh

in any case you should check logs of all the dask pods for errors.

**Comment by zonca** [comment]
check also if any pod is just waiting instead of executing

**Comment by julienchastang** [comment]
> can you check that your "install dask gateway" script specifies 0.9.0?

Indeed, I was using the wrong version. Thanks for pointing that out.

**Comment by julienchastang** [comment]
Is there a way to shutdown clusters? I accidentally created too many:

```
[ClusterReport<name=jhub.4fb6f421a13247e09957c35b0508c56e, status=RUNNING>,
 ClusterReport<name=jhub.0efa52c67fcd4e919caade1b9d28dbda, status=RUNNING>,
 ClusterReport<name=jhub.98e6af9fa284452d9a4be9f29c46c948, status=RUNNING>]
```

At any rate, I am seeing:

```
OSError: Timed out during handshake while connecting to gateway://traefik-dask-gateway:80/jhub.0efa52c67fcd4e919caade1b9d28dbda after 10 s
```

There is information in the logs, but I am not sure what is relevant and what isn't. BTW, you have access to https://js-169-121.jetstream-cloud.org/ so you should be able to try it if you'd like.

**Comment by julienchastang** [comment]
Never mind.... Something like this should work:

```
clusters = gateway.list_clusters()
c = gateway.connect(clusters[0].name)
c.shutdown()
```

though it takes a surprisingly long time for it to shutdown.

**Comment by julienchastang** [comment]
The instructions are maybe a little strange in the sense that there is a call to 

```
gateway.list_clusters()
```

before the cluster is created (see next cell). I would suggest moving that call down a cell, if I am understanding this right.

**Comment by julienchastang** [comment]
Hi Andrea (@zonca). I eventually got this to work though with some caveats. [I wrote a notebook about it to capture the entire experience](https://gist.github.com/julienchastang/677d6c90de6589e333bf249ddde45892).

**Comment by zonca** [comment]
thanks, Jetstream 2 is coming soon, so I'll take a look at this again on Jetstream 2.
