### ISSUE TITLE
Test latest pangeo on the kubespray-based deployment

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#5]
The purpose is to deploy again the latest kubespray deployment:

https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray.html

and check that the pangeo images works fine, including launching a private dask cluster for each user (I had tested it previously at https://zonca.github.io/2018/06/private-dask-kubernetes-jetstream.html)

**Comment by zonca** [comment]
@rsignell-usgs first I setup autobuild on DockerHub, see:

* https://cloud.docker.com/repository/registry-1.docker.io/zonca/pangeo_notebook_rsignell
* https://cloud.docker.com/repository/registry-1.docker.io/zonca/pangeo_worker_rsignell

I could not build out of your repository so I am building my fork (I gave you write access):

https://github.com/zonca/pangeo-helm-chart/tree/esipfed

If you make any changes to that branch, the Docker images are going to be automatically updated (it is quite slow, it takes often ~45 min)

**Comment by rsignell-usgs** [comment]
Great to see the progress @zonca !

**Comment by zonca** [comment]
it worked great, see some notes here: https://zonca.github.io/2018/12/kubernetes-jetstream-kubespray-pangeo.html

**Comment by zonca** [comment]
ok, now I am testing Zarr on object store again, following my old tutorial at: https://zonca.github.io/2018/03/zarr-on-jetstream.html

Reading works fine, I can execute the notebook at https://gist.github.com/zonca/bda69ab917bde831845d530e52eae6e5, just need to replace `JETSTREAM_SWIFT_ENDPOINT` with the correct value (email me if you don't know it)
