### ISSUE TITLE
JS2 Jhub Deployment questions

### ISSUE THREAD

**Issue by ktyle** [zonca/jupyterhub-deploy-kubernetes-jetstream#50]
Hi, I'm following the instructions on https://zonca.dev/2022/03/jetstream2-jupyterhub.html and have a couple of questions and deployment problems:

1. Once the k8s master and client nodes are up and running, following the https://zonca.dev/2022/03/kubernetes-jetstream2-kubespray.html tutorial, are we supposed to be logged into the k8s-master node to do the various steps in the jetstream2-jupyterhub tutorial?
2. It looks like at least some of the commands need to be run with sudo privileges (e.g., the `kubectl` commands). Is there a general rule as to when one needs to use `sudo`?
3. I'm running into an error when I run `install_jhub.sh`: 
```sudo bash install_jhub.sh
Release "jhub" does not exist. Installing it now.
Error: failed to download "jupyterhub/jupyterhub" at version "1.2.0"
```
any ideas?

**Comment by ktyle** [comment]
I resolved (3) by repeating the `configure_helm_jupyterhub.sh` script, but with `sudo`

**Comment by ktyle** [comment]
The issue now is that an external IP is not getting assigned: (I masked the internal cluster IP's in the output below)

```
 sudo kubectl get service --namespace jhub
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
hub            ClusterIP      10.x.x.x  <none>        8081/TCP       29m
proxy-api      ClusterIP      10.y.y.y    <none>        8001/TCP       29m
proxy-public   LoadBalancer   10.z.z.z   <pending>     80:32560/TCP   29m
```

**Comment by zonca** [comment]
No on jet stream there is no service providing an external IP automatically like a load Balancer on Amazon.

However, you attach a floating IP to your master instance and that makes your cluster reachable from outside.

**Comment by ktyle** [comment]
Thanks @zonca ... I do have the floating IP set for the master instance. Would I then point my browser to port 8081 at that 149.x.x.x IP address?

**Comment by zonca** [comment]
If ingress is configured correctly then you should be able to connect to the domain

**Comment by zonca** [comment]
Via http

**Comment by ktyle** [comment]
Thanks @zonca; all is looking good now!
