### ISSUE TITLE
Clarification: NFS volumes on more than one node

### ISSUE THREAD

**Issue by ana-v-espinoza** [zonca/jupyterhub-deploy-kubernetes-jetstream#58]
When following your [tutorial](https://www.zonca.dev/posts/2023-02-06-nfs-server-kubernetes-jetstream) on how to deploy an NFS drive, I was inspecting the various yaml files. I noticed, in particular, the [access mode](https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/blob/master/nfs/create_nfs_volume.yaml#L8) in `create_nfs_volume.yaml` is set to `ReadWriteOnce`.

The Kubernetes [docs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) say that this access mode only allows the NFS volume to be mounted onto a single node. This would be a problem for multi-node clusters where single user pods could be scheduled on more than one worker node. Is this the correct interpretation of this option?

If so, consider changing the accessMode to `ReadWriteMany` and/or updating the tutorial to mention this configuration option.

@julienchastang 

Thanks,
-- Ana

**Comment by zonca** [comment]
No, that volume is only mounted on the NFS server itself.
It is the back end storage for the server.

What is mounted on the user volumes is a specified in the Jupiter hub configuration

**Comment by ana-v-espinoza** [comment]
Ah right! It's not the openstack volume that will be mounted onto multiple nodes, but rather the exported NFS volume, correct?

Thanks for the clarification,
-- Ana

**Comment by zonca** [comment]
exactly
