### ISSUE TITLE
kubectl delete namespace jhub stuck

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#59]
I've noticed that `kubectl delete namespace jhub` is getting consistently stuck. It does indeed seem to still delete the `jhub` namespace but my concern is that it is orphaning resources (e.g., pvc volumes).

**Comment by zonca** [comment]
ok, I can do some testing to clarify this

**Comment by julienchastang** [comment]
To add a bit more information, if you

`kubectl edit svc proxy-public -n jhub`

and change

```
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
```

to 

```
  finalizers: []
```

that will allow the name space to be deleted.

**Comment by zonca** [comment]
I am looking into this, documentation about that finalizer is available here:
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#garbage-collecting-load-balancers

I have tested deploying a fresh deployment of JupyterHub and I do not see the finalizer. So deleting the namespace completes successfully.
However I am not sure if some operation might triggering adding the finalizer to the service.
@ana-v-espinoza any suggestion?

**Comment by zonca** [comment]
actually I think I figured it out, I switched the proxy to be a clusterIP instead of a load balancer.
This should solve this issue, and also avoids the unconvenience of seeing a load balancer with a "pending" external IP.

**Comment by ana-v-espinoza** [comment]
@zonca 

Do you mind sharing what you did to change the Service type? I want to be sure we're on the same page here, as this is what I would do:

If changing the service type of an existing proxy-public service:
`kubectl edit service -n jhub proxy-public` and changing `spec.type` to `clusterIP`.

To ensure the service type is `clusterIP` for a new cluster, add the following to `secrets.yaml` ([reference](https://z2jh.jupyter.org/en/stable/resources/reference.html#proxy-service-type)):
```yaml
---
proxy:
  service:
    type: "clusterIP"
```

Then install as usual.

Come to think of it, this second method *should* work for existing installations, as helm would redeploy the service whenever the change is made.

**Comment by zonca** [comment]
see the commit attached to the issue,
same thing you did
