### ISSUE TITLE
Update kubespray to 2.8.2

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#6]
I am using a version of kubespray from August 2018, as I am hitting some stability issues,
I think it is time to update to a newer version of `kubespray`, which also installs a newer Kubernetes
so I have been working on adapting 2.8.2 to Jetstream, see progress here: https://github.com/zonca/jetstream_kubespray/pull/5

@julienchastang @rsignell-usgs I'll send updates here when I have news

**Comment by zonca** [comment]
I got it working, published a new blog post https://zonca.github.io/2019/02/kubernetes-jupyterhub-jetstream-kubespray.html

I also tested the brand new 0.8 release of zero-to-jupyterhub.

@julienchastang please give it a try!

**Comment by julienchastang** [comment]
Alrighty, I will give this a shot as well.

**Comment by julienchastang** [comment]
Just to be clear,  scaling up and down is still done on the information inside of `cluster.tf`? Subsequently, `k8s_scale.sh` and `k8s_remove_node.sh` work with whatever has been defined in `cluster.tf` to scale up or down, is that correct?
