### ISSUE TITLE
Binderhub on JS2 Documentation

### ISSUE THREAD

**Issue by ktyle** [zonca/jupyterhub-deploy-kubernetes-jetstream#61]
Hi @zonca ,

I'm embarking on a new Binderhub deployment on JS2, this time with https and OAuth. 

On the [JS2 Binderhub docs](https://docs.jetstream-cloud.org/general/k8sbinderhub/), there are a couple sections that don't match what I'm seeing after I clone your repo:

```
Enter the binderhub folder.
```

There is no `binderhub` folder in this repo

```
The repository provides a template named config_template.yaml to create config.yaml, this file contains all of the configuration items needed to setup the following items, see the links for the relevant documentation:
```

There is no `config_template.yaml` anywhere in the directory tree.

**Comment by zonca** [comment]
thanks @ktyle, you are right, I must have forgotten to merge the branch, I'll look into it.

**Comment by zonca** [comment]
@ktyle I remember a couple of months ago I did a dangerous `git clean -dfx` and lost some files in that directory tree,
anyway this time it seems I was saved by `~/vimbackup`.

Please try to use the files from https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/tree/master/binderhub
and check if everything works.

If not, please let me know and I can test it myself.
Consider also that I developed that back in October last year, so something might have broken in the meantime.

**Comment by ktyle** [comment]
Thanks @zonca ! I have those two files now. 

In `install_binderhub.sh`, is there any need for the `source config_vars.sh` line, since the two variables can be set right in the `install_binderhub.sh` file?

**Comment by zonca** [comment]
the idea is that this way you can commit `install_binderhub.sh` to version control, and keep config_vars.sh secret

**Comment by ktyle** [comment]
I'm also a bit unclear about the secure https configuration.

The documentation states to follow the [zero to binderhub secure https docs](https://binderhub.readthedocs.io/en/latest/https.html).

However is it also necessary for JS2 to follow what you describe [here](https://www.zonca.dev/posts/2020-03-13-setup-https-kubernetes-letsencrypt.html) for a Jupyterhub-only deployment?

**Comment by zonca** [comment]
You need to follow both.
First you use my tutorial to deploy the cluster issuer.
When you follow the binder hub tutorial to change the configuration of binder hub

**Comment by ktyle** [comment]
Thanks! I've got https and GitHub Oauth working now! I hope to put in a PR to further clarify the documentation.

**Comment by zonca** [comment]
That would be very much appreciated. Thanks!

**Comment by zonca** [comment]
@ktyle if you have time to improve the docs, that would be great!

**Comment by ktyle** [comment]
@zonca I have been on vacation in France/UK for a couple weeks but will get to it on my return later this week!

**Comment by zonca** [comment]
@ktyle just a reminder on this

**Comment by ktyle** [comment]
Hi @zonca sorry for the delay. I was at the Project Pythia hackathon all last week (which made great use of our existing JS2 binderhub, by the way). I am going to test the current deployment workflow on my ACCESS Campus Champions allocation this week ... I needed to have JS2 admins provide me with an additional router since the only one available to me was the auto-allocated router, which I believe you are still modifying the workflow to support.

**Comment by zonca** [comment]
Interesting about the  Project Pythia hackathon, how many people did you have connected? how many jetstream vms were you using?

**Comment by ktyle** [comment]
We had about 40 folks actively participating. This was on a 4-node k8s cluster (m3. large for the master; m3.xl for the nodes). Most of the notebooks ran fine within the prescribed memory/cpu limits. There was a group of participants who needed a GPU-capable Binderhub, so I'll be focusing on that after I get back from SciPy (so expect some more queries about that). 

In the meantime, I am just about ready to submit a PR to the js2docs repository with my first round of suggested edits to the [JS2 Binderhub document](https://docs.jetstream-cloud.org/general/k8sbinderhub/) . Sorry it has taken a while.
