### ISSUE TITLE
Cannot delete subnet, ports

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#62]
I have been experimenting with terraform,
I got into a configuration where there is no way to delete a subnet.

The subnet id is:

`3d7e56ed-6e7b-4efc-9948-1e285fbbfe9c`

@zacharygraber

**Comment by zonca** [comment]
```
o port list | grep 3d7
| 4c86c134-29bd-4d07-92d1-08200794f06d |      | fa:16:3e:e6:34:64 | ip_address='10.1.28.227', subnet_id='3d7e56ed-6e7b-4efc-9948-1e285fbbfe9c' | ACTIVE |
| 89e9f501-ab43-4062-a77c-bb14c89ae66b |      | fa:16:3e:ac:8d:55 | ip_address='10.1.28.2', subnet_id='3d7e56ed-6e7b-4efc-9948-1e285fbbfe9c'   | ACTIVE |
```

**Comment by zonca** [comment]
I can delete 1 of the ports, but it is automatically re-created, not sure by what.

**Comment by zacharygraber** [comment]
> I can delete 1 of the ports, but it is automatically re-created, not sure by what.

Which one?

**Comment by zonca** [comment]
I deleted `89e9f501-ab43-4062-a77c-bb14c89ae66b`

**Comment by zonca** [comment]
and now there is another one:

```
o port list | grep 3d7
| 4c86c134-29bd-4d07-92d1-08200794f06d |      | fa:16:3e:e6:34:64 | ip_address='10.1.28.227', subnet_id='3d7e56ed-6e7b-4efc-9948-1e285fbbfe9c' | ACTIVE |
| c6147875-6b77-47f5-9e7d-cf2612ac9b0d |      | fa:16:3e:b2:d7:82 | ip_address='10.1.28.2', subnet_id='3d7e56ed-6e7b-4efc-9948-1e285fbbfe9c'   | ACTIVE |
```

**Comment by zonca** [comment]
I would like just everything deleted, subnet and all ports

**Comment by zacharygraber** [comment]
Openstack won't let us delete the subnet because of this port existing:

![image](https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/assets/60680903/7b9a2ffd-8609-4b5a-9914-35f0a30021f1)

`4c86...` is on the subnet, by it's owned by `router_centralized_snat`, and ports owned by that disallow any edits. I'm going to check with some folks about this.

**Comment by zonca** [comment]
I noticed that there was also a load balancer resource created not sure by what process. I deleted that manually in Horizon. I'm wondering if it could be related.

**Comment by zacharygraber** [comment]
The solution ended up being
`openstack router unset --external-gateway  15cc195f-02d4-4d9b-ae24-5b2e9e52a13a`
which got rid of the offending port(s) and let us delete the subnet.

**Comment by zonca** [comment]
great, thanks! I'll do it myself if it happens again!
