### ISSUE TITLE
Feedback for Latest Dask Workflow (2023.9.0)

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#65]
Hi Andrea.

Thanks for putting together [the latest Dask workflow](https://www.zonca.dev/posts/2023-09-28-dask-gateway-jupyterhub). I have a few suggestions for improvement :-)

-   The blog mentions version `2023.9.0` but I found two references to version `2022.4.0` in `dask_gateway/install_dask-gateway.sh` and `dask_gateway/config_dask-gateway.yaml`. Should I change them both to the newer version?
-   I believe the `apiToken: "TOKEN"` needs to be set (with the help of `openssl` e.g., `openssl rand -hex 32`) in `dask_gateway/config_dask-gateway.yaml` and `dask_gateway/config_jupyterhub.yaml` and it needs to be the same, right? Otherwise, I was seeing errors in one of the k8s pods.
-   There are a number of dask related directories in `zonca/jupyterhub-deploy-kubernetes-jetstream` such as

```sh
./jupyterhub-deploy-kubernetes-jetstream/dask_gateway
./jupyterhub-deploy-kubernetes-jetstream/dask_gateway/dask-hub
./jupyterhub-deploy-kubernetes-jetstream/dask_shared
./jupyterhub-deploy-kubernetes-jetstream/gateway-dask-zarr
./jupyterhub-deploy-kubernetes-jetstream/gateway-dask-zarr/dask-gateway-zarr
```

but it is only the files in `./jupyterhub-deploy-kubernetes-jetstream/dask_gateway` that we are concerned with, correct? That's all you mention in your blog, but just double-checking.

I am also seeing these errors or problems:

-   Navigating to <https://dtest-1.ees220002.projects.jetstream-cloud.org/services/dask-gateway/> yields `404: Not Found` error.
-   No external IP:

```sh
$ kubectl --namespace=jhub get service traefik-dask-gateway
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
traefik-dask-gateway   LoadBalancer   10.233.59.12   <pending>     80:31471/TCP   17h
```

Note the `EXTERNAL-IP` is `<pending>` in contrast to the blog which has a defined IP. Unfortunately, I believe this means I cannot create a dask gateway since I don't have an IP, right?

The default notebook is `pangeo/base-notebook:2021.06.05` which is quite old. Would it be possible to reference something more up-to-date?

Thanks

**Comment by julienchastang** [comment]
I also found another clue. When doing:

```
kubectl logs kube-controller-manager-dtest-1 -n kube-system
```

I found:

```
E1017 21:24:46.415166       1 core.go:92] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
```

**Comment by zonca** [comment]
sorry I pushed none of my configuration changes!!

Token is not needed in the last version of dask.

IP works fine:

```
kj get svc traefik-dask-gatewayNAME                   TYPE           CLUSTER-IP     EXTERNAL-IP       PORT(S)        AGE
traefik-dask-gateway   LoadBalancer   10.233.43.51   149.165.xxx.xxx   80:32752/TCP   20d
```

**Comment by zonca** [comment]
and now I just connect directly to that public ip, without using jupyter proxy

**Comment by julienchastang** [comment]
Hi Andrea. Thanks for the quick response. I implemented the changes [described here](https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/commit/c2a3e5e49848650fb238e3dda435d4d65486898f), but I still get the same result:

```sh
$ kubectl --namespace=jhub get service traefik-dask-gateway
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
traefik-dask-gateway   LoadBalancer   10.233.35.195   <pending>     80:30285/TCP   15m
```

I also deleted the `jhub` namespace and started over just to be on the safe side.
 
In addition,

```python
import requests
requests.get("http://traefik-dask-gateway/services/dask-gateway/api/health").content
```

now returns `b'404: Not Found'`. My earlier attempt when I first reported this problem yielded the expected result.

Thanks again.

**Comment by zonca** [comment]
@julienchastang please make sure that the load balancer resource is deleted.
better check in Horizon.

**Comment by zonca** [comment]
also, the pending IP could be a problem related to having enough security groups and security group rules.
I had a similar problem and @julianpistorius from the Jetstream team was able to fix it.
Can you open a ticket and ask for a larger number of security groups and rules, I now have 100 security groups and 1000 rules.

**Comment by zonca** [comment]
it is useful if you check in Horizon what is the state of your Load Balancer, under Network, is it in "ERROR" state?

**Comment by julienchastang** [comment]
There is indeed ONE loadbalancer (Created At 2023-07-28T21:43:16 so I don't think it is relevant to what we are discussing here), and I'm a little nervous about deleting it. Also I think we have enough resources in the security group (Used 65 of 100) and security group rules category (Used 207 of 300).

Moreover, [as mentioned previously](https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/issues/65#issuecomment-1769323400), I don't think a LB was ever created to begin with.

![image](https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/assets/229955/a4bcb58b-853f-4ca2-bd4e-80395b0b099f)

**Comment by zonca** [comment]
There should not be any load balancer after you take off Jupiter hub but it looks like It is not automatically deleted

**Comment by zonca** [comment]
That should not be any load balancer after you take off Jupiter hub but it looks like It is not automatically deleted

**Comment by zonca** [comment]
Actually, it could also be that you created the application credentials in the past and they do not have the permission to create the load balancer

**Comment by julienchastang** [comment]
@jlf599 do we, at present,  have the permissions/capability of creating/launching loadbalancers?

@zonca at what point is the load balancer created? Terraform? Ansible? via K8s?

**Comment by zonca** [comment]
Just check your app credential on Horizon
It tells you if you have load balancer permission

**Comment by zonca** [comment]
Created by K8S, by helm when you install jhub

**Comment by jlf599** [comment]
> @jlf599 do we, at present, have the permissions/capability of creating/launching loadbalancers?
> 
> @zonca at what point is the load balancer created? Terraform? Ansible? via K8s?

I'm not sure -- though I think from discussions over the last few days that if you presently do not, if you generate a new application credential that it should. 

Confirmed -- new application credentials will get the load_balancer cred as part of it.

**Comment by ana-v-espinoza** [comment]
Hey all,

I took a look at this yesterday evening as well. The LoadBalancer Julien and I are seeing is from one of our clusters that is currently operational. I think this was created when JS2 first got Octavia and before Andrea patched the proxy Service to be of type ClusterIP. I had provisioned that cluster, so K8s was/is using my credentials.

It may be worth noting that the log message that Julien was seeing may be a red herring (caused by a race condition when deploying K8s via Kubespray maybe?). I see the same log message in the cluster with the operational LB:

```
[openstack@f8b47e0acc02 ~]$ kubectl logs -n kube-system kube-controller-manager-<operational-cluster>-1 | grep LoadBalancer
E1002 03:00:28.591369       1 core.go:92] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
```

While the *cloud controller* pod (`openstack-cloud-controller-manager-xxxxx`)  is clearly able to get openstack to provision the LB (on the operational cluster).

---

After we ensure that Julien need only update his openstack creds on the cluster, I'll update the JHub to make that service a ClusterIP type as well. This should cause helm/K8s/openstack to destroy the LB. Until then, For the time being we could use this cluster and it's LB as an example of "what works" to compare with the problem Julien was having yesterday.

@julienchastang , Andrea has a [tutorial](https://www.zonca.dev/posts/2023-03-23-update-openstack-credentials-kubernetes) for how to update the openstack credentials used by K8s. Thank's @zonca ! This actually came in handy only a few weeks after the initial posting of the tutorial when my own creds expired.

As always, thank you both for your help and input.

**Comment by julienchastang** [comment]
OK, I got it to work:

```sh
$ kubectl --namespace=jhub get service traefik-dask-gateway
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP       PORT(S)        AGE
traefik-dask-gateway   LoadBalancer   10.233.43.64   149.165.xxx.xxx   80:30482/TCP   74m
```

The crux of the matter was the application credentials. @jlf599, note the Horizon application credentials interface is counter intuitive for the selection of roles. You have to shift highlight `load-balancer_member`, `reader`, `member`. Not obvious. I did have to rebuild the cluster b/c somehow something from the old creds was mucking up the works.

Beyond that, [Andrea's instructions](https://www.zonca.dev/posts/2023-09-28-dask-gateway-jupyterhub) worked out of the box. Note, Andrea, I did not use the changes in https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/commit/c2a3e5e49848650fb238e3dda435d4d65486898f which I tried to use but resulted in various errors:

```sh
@@ -12,7 +12,7 @@ gateway:
     type: jupyterhub

     jupyterhub:
-      apiToken: "TOKEN"
+      apiToken: "xxx"

   extraConfig:
     # Note that the key name here doesn't matter. Values in the
@@ -30,7 +30,7 @@ gateway:
         c.Backend.cluster_options = Options(
             Integer("worker_cores", 2, min=1, max=4, label="Worker Cores"),
             Float("worker_memory", 4, min=1, max=8, label="Worker Memory (GiB)"),
-            String("image", default="ghcr.io/dask/dask-gateway:2022.4.0", label="Image"),
+            String("image", default="ghcr.io/dask/dask-gateway:2023.9.0", label="Image"),
             handler=option_handler,
         )

diff --git a/dask_gateway/config_jupyterhub.yaml b/dask_gateway/config_jupyterhub.yaml
index 458c70e..51de294 100644
--- a/dask_gateway/config_jupyterhub.yaml
+++ b/dask_gateway/config_jupyterhub.yaml
@@ -8,4 +8,4 @@ hub:
     dask-gateway:
       # This makes the gateway available at ${HUB_URL}/services/dask-gateway
       url: http://traefik-dask-gateway
-      apiToken: "TOKEN"
+      apiToken: "xxx"
diff --git a/dask_gateway/install_dask-gateway.sh b/dask_gateway/install_dask-gateway.sh
index d2f339b..8e2d1e9 100644
--- a/dask_gateway/install_dask-gateway.sh
+++ b/dask_gateway/install_dask-gateway.sh
@@ -4,7 +4,7 @@ NAMESPACE=jhub
 helm upgrade  \
     --install \
     --repo=https://helm.dask.org \
-    --version 2022.4.0 \
+    --version 2023.9.0 \
     --namespace $NAMESPACE \
     --values config_dask-gateway.yaml \
     $RELEASE \
```

Beyond that, the cluster appears to be working. I'll give more updates if I have additional problems. Thanks all for everyone's help :-)

**Comment by zonca** [comment]
good, I have almost completed a small tutorial on how to use a load balancer in front of JupyterHub itself, changes are minor

**Comment by julienchastang** [comment]
Separately, do you believe it is possible to have a more modern combination of worker / client / scheduler conda environments? I remember when I did this last in the Spring of 2022, I had a lot of trouble finding a combination that worked.

**Comment by zonca** [comment]
not sure what you are referring to, we are using `2023.9.0` for the dask containers

**Comment by jlf599** [comment]
@julienchastang - I'm not certain we can do much about Horizon's functionality, but I'll let the support team know to document it.

**Comment by julienchastang** [comment]
@zonca if I remember correctly from the last go around, the conda environment had to be in sync with respect to the Dask version. At present `2023.9.0` vs. `2021.6.0`.

```
(notebook) jovyan@jupyter-julienchastang:~$ pip list | grep -i dask
dask                          2021.6.0
dask-gateway                  0.9.0
dask-kubernetes               2021.3.1
dask-labextension             5.0.2
```

**Comment by zonca** [comment]
I see, you are referring to the singleuser image, which image are you using?

**Comment by julienchastang** [comment]
Same one as the one referred to in your docs until recently:

```
singleuser:
  image:
    name: pangeo/base-notebook
    tag: 2021.06.05
```

BTW, if you are looking for a Dask notebook to showcase during your workshop, [this one](https://github.com/julienchastang/science-gateway/blob/uwd-2023-fall/jupyter-images/fall-2023/uwd/wrf.ipynb) is pretty cool.

I sadly will not be at the SGCI conference this year.

**Comment by zonca** [comment]
I'm actually using https://hub.docker.com/layers/jupyter/scipy-notebook/2023-10-02/images/sha256-28ebcabf1f39bf6369d121d908177cc180abe164b7a615e65a1036db9f834fa5?context=explore and then installing `dask-gateway` with `pip` now. It is a bit ugly to install packages with `pip`, but I think it is fine for the tutorial. So I plan to switch the tutorial to using `scipy-notebook`, what do you think?

**Comment by julienchastang** [comment]
I have [this](https://github.com/Unidata/science-gateway/pull/871/files) working at present. It is still a work in progress, but it is looking good so far. You might be interested in the `dask/Dockerfile`. I have the Dask dashboard working as expected so that's a good sign. I am now tracking down a missing dataset, but that's a different story.

**Comment by julienchastang** [comment]
[This worked during the 2023 fall semester so closing.](https://github.com/Unidata/science-gateway/pull/871)
