### ISSUE TITLE
Create branch_v2.21.0_gpu branch

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#69]
https://github.com/julienchastang/jetstream_kubespray/tree/branch_v2.21.0_gpu

**Comment by zonca** [comment]
@julienchastang is this related to one of the other issues @ana-v-espinoza created?

**Comment by julienchastang** [comment]
Sorry for the delayed response. I was at a conference followed by an illness. I believe there is a GPU branch that parallels `v2.18.0` so requesting something similar for `v2.21.0`. I believe the branch I have above captures what is needed which is a small number of changes. I think the other issues referred to may be for the hybrid hub.

**Comment by julienchastang** [comment]
PS I think the other GPU issues relate to a more fundamental re-examination in how we deploy GPU Hubs specifically with respect to GPU image sizes and base image considerations.

**Comment by zonca** [comment]
Very good. So I will follow up on the GPU hybrid pull request.
