### ISSUE TITLE
Scale cluster manually

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#7]
https://zonca.github.io/2019/02/scale-kubernetes-jupyterhub-manually.html

@julienchastang it looks like updating `kubespray` did the trick, I haven't got namespaces issues this time.
Please let me know if you still find issues.

/cc @rsignell-usgs

**Comment by julienchastang** [comment]
Excellent. Do you think this is compatible with a current kubernetes deployment (e.g., the kube clusters we have already deployed using these methods).  Relatedly, is it also possible to update kubernetes itself, safely without loosing user data via the ansible playbook? Basically, I want a seamless user experience as the jupyterhub migrates forward.

**Comment by zonca** [comment]
It wasn't working with my older kubespray deployment due to errors in
namespaces.

**Comment by zonca** [comment]
from @julienchastang :

> Just to be clear, scaling up and down is still done on the information inside of cluster.tf? Subsequently, > k8s_scale.sh and k8s_remove_node.sh work with whatever has been defined in cluster.tf to scale up or > down, is that correct?

`k8s_scale.sh` only installs kubernetes any new machine that you need first to create with `terraform`, and you create it in terraform modifying `cluster.tf`.

`k8s_remove_node.sh` doesn't care about `cluster.tf`, it only removes a node from the kubernetes cluster (but leaves the Openstack image running).

**Comment by julienchastang** [comment]
One thing I noticed is that scaling up works, but then when I remove nodes during the "scale down" process, you cannot subsequently scale up again. The nodes cannot be reclaimed. So the workflow I am talking about is scale up, scale down, and scale up again.

```
kube-exp-k8s-master-1      : ok=25   changed=3    unreachable=0    failed=0
kube-exp-k8s-node-nf-1     : ok=247  changed=15   unreachable=0    failed=0
kube-exp-k8s-node-nf-2     : ok=22   changed=4    unreachable=0    failed=1
kube-exp-k8s-node-nf-3     : ok=22   changed=4    unreachable=0    failed=1
```

Here I added 2 nodes (`kube-exp-k8s-node-nf-2`, `kube-exp-k8s-node-nf-3`), then I drained them, then I tried adding them again, and got the error above. I've been able to reproduce this a few times now so I think it is a real problem. Steps to reproduce roughly:

```
sh terraform_apply.sh
sh k8s_scale.sh
sh k8s_remove_node.sh kube-exp-k8s-node-nf-2
sh k8s_remove_node.sh kube-exp-k8s-node-nf-3
teardown.sh -n kube-exp-k8s-node-nf-2
teardown.sh -n kube-exp-k8s-node-nf-3
sh terraform_apply.sh
sh k8s_scale.sh
```

(`teardown.sh` simply calls `openstack server stop` followed by `openstack server delete`)

**Comment by zonca** [comment]
What is the operation that failed?

**Comment by julienchastang** [comment]
`sh k8s_scale.sh` (the second time around) will yield the "failed" messages above.

**Comment by zonca** [comment]
That is the summary at the end, but in the full log what is the actual
ansible task that failed?

**Comment by julienchastang** [comment]
[Here is the output](https://gist.github.com/julienchastang/d99a6a081aa6e80033524c4860567c52). It has some annoying escape codes so hopefully you can read it. Though in this case `kube-exp-k8s-node-nf-2` actually succeeded but `kube-exp-k8s-node-nf-3` still failed. I was working on the hypothesis that once a node scales down you cannot scale it up again (even if it has been deleted via openstack and recreated via terraform), but this output partially shows that is not true.

[Line 600 looks suspect, maybe](https://gist.github.com/julienchastang/d99a6a081aa6e80033524c4860567c52#file-out-txt-L600).

[Maybe this `flush-cache` option is important.](https://github.com/kubernetes-sigs/kubespray/issues/1859#issuecomment-338969535).

**Comment by zonca** [comment]
yes, can you do a couple of tests using `flush-cache`?

**Comment by julienchastang** [comment]
Yes, that seems to work. I will submit a PR here shortly. I can now scale up and down without issue.

**Comment by zonca** [comment]
Awesome, thanks for fixing this!!
