### ISSUE TITLE
Future PR: "Hybrid" CPU/GPU Cluster and "Soft Scaling"

### ISSUE THREAD

**Issue by ana-v-espinoza** [zonca/jupyterhub-deploy-kubernetes-jetstream#70]
CC: @julienchastang 

# Hybrid Cluster

Recently, I've been working on creating a "hybrid" cluster workflow which uses both "regular CPU" (i.e. `m3.*` type) and GPU (`g3.*`) Jetstream flavors.

An example of a scenario where this could be useful is when the majority of your JupyterHub's users do not need GPU resources and you want to conserve Jetstream GPU SUs, in which case you could have, e.g. 5 `m3.medium` instances for general use and a single `g3.small` for GPU capability.

Documentation and a PR to jetstream_kubespray to follow in the future.

In short, I'm using the `k8s_nodes` [option of Kubespray](https://github.com/zonca/jetstream_kubespray/blob/branch_v2.21.0/contrib/terraform/openstack/README.md#k8s_nodes), assigning GPU nodes a new ansible host group, and using group_vars to apply the necessary changes to `containderd` for GPU instances only.

# "Soft Scaling"

My original use case for the hybrid cluster is an extension of the example above. One of the courses we're deploying a cluster for will be making use of GPUs intermittently throughout the semester. So as to not have GPU instances running at all times, I've created a hybrid cluster with some amount of each instance flavor, with the intention to make the GPU instances available only when necessary.

The GPU instances are then drained, cordoned, and shelved (a process I've been referring to as ["soft scaling"](https://github.com/Unidata/science-gateway/tree/master/vms/jupyter#soft-scaling-a-cluster)). These instances are then made available to the cluster by unshelving the instances and uncordon-ing them, a process that can take less than 5 minutes.

We've applied this soft scaling procedure successfully and without issue in the past. The original use case was to reduce the "idle" SUs used by a cluster intended for multiple workshops spread over the course of the summer and early fall of 2023. That is, this cluster was required to serve a large amount of people, but only in quick bursts.

I believe that this technique could be useful to the wider Jetstream2 community, and that a blog post or an addition to the JS docs could be warranted. I'll leave this up to the discretion of @zonca

**Comment by zonca** [comment]
Nice! absolutely, I was wondering if this were possible, and it looks like you found an elegant solution. It would be useful to have 2 separate blog posts / PR for the 2 functionalities.

**Comment by ana-v-espinoza** [comment]
Mentioning these PRs here as well in case somebody else runs across this issue.

CPU/GPU Hybrid Cluster: https://github.com/zonca/jetstream_kubespray/pull/29
Soft Scaling Docs: PR #71

**Comment by zonca** [comment]
excellent as always @ana-v-espinoza 
I'll give feedback on the other PRs
