### ISSUE TITLE
"Soft" Auto Scaling Hack

### ISSUE THREAD

**Issue by ana-v-espinoza** [zonca/jupyterhub-deploy-kubernetes-jetstream#78]
CC: @julienchastang 

In the absence of true auto-scaling on Jetstream2, you created the scripts found in the [hacktoscalar directory](https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/tree/master/hacktoscaler), which uses the "hard" scaling method of provisioning new nodes before adding them to the cluster (or tearing them down, in the case of a scale down).

I want to revisit this workflow to use soft scaling instead and will be working on this soon.

Best,

ana v. e.

**Comment by zonca** [comment]
Consider the jet stream team is now working on a new method to deploy kubernetes 

This is going to be based on cluster apis 

Once that is available we will have native auto scaling

**Comment by zonca** [comment]
https://gitlab.com/jetstream-cloud/project-mgt/-/issues/108

**Comment by zonca** [comment]
This won't be necessary, we will have the new Openstack Magnum based on Cluster API coming soon.
