### ISSUE TITLE
Ansible playbook fails with Jetstream2 Featured-Minimal-Ubuntu24 image

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#81]
Ansible playbook fails with Jetstream2  `Featured-Minimal-Ubuntu24`. I have a 7 MB playbook log output with maximum verbosity. I am a little nervous about sharing sensitive information through the log file so I will share that privately. The main thing I am seeing are ssh errors.

**Comment by zonca** [comment]
thanks @julienchastang, posted to https://gitlab.com/jetstream-cloud/general/image-build-pipeline/-/issues/40

**Comment by zonca** [comment]
Kubespray does not support Ubuntu 24, this works fine with Ubuntu 22
