### ISSUE TITLE
Using Manila shares instead of NFS servers

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#84]
@ana-v-espinoza @julienchastang as discussed today at Gateways 2024 with @julianpistorius, instead of using NFS servers to create a shared mount to all JupyterHub users, as I do in:

https://www.zonca.dev/posts/2023-02-06-nfs-server-kubernetes-jetstream

You can instead use Manila Ceph Shares:

https://www.zonca.dev/posts/2022-12-05-jetstream2-kubernetes-manila.html

at the bottom of that tutorial it also shows how to mount those into JupyterHub.

In order to simplify copying data into that shared disk, it might be useful to use the `mount_ceph.py` script which is included in Exosphere. I plan to write a small tutorial on how to generate the configuration for that script, see https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/issues/82. This would allow users to mount that disk directly on their local machine and then do a local copy.

The other option would be to run an SSH server inside Kubernetes, so an hybrid between the `ceph_pod` in https://www.zonca.dev/posts/2022-12-05-jetstream2-kubernetes-manila and the SSH server in https://www.zonca.dev/posts/2023-02-06-nfs-server-kubernetes-jetstream.

**Comment by ana-v-espinoza** [comment]
Hey Andrea,

I was looking through the [documentation](https://kubernetes.io/docs/concepts/storage/volumes/#cephfs) on the cephfs volume type on the Kubernetes website after our discussion. It looks like the cephfs volume type was deprecated in K8s 1.28 and removed in 1.31. Currently, our Kubespray workflow [deploys k8s 1.25](https://github.com/zonca/jetstream_kubespray/blob/6ba36564107c34a6261f2ae44d05aa344277e10e/roles/kubespray-defaults/defaults/main.yaml#L18), so we're safe for now, albeit a bit behind on the times!

The recommended method of interacting with ceph is now [ceph-csi](https://github.com/ceph/ceph-csi/tree/devel), which will function similarly to the `cinder-csi` we currently use to provision PVs by interacting with OS/Cinder. While this is probably not too big of a concern at the moment, eventually we may run across having to tackle this problem.

Forgive me if I use the incorrect terminology below, as I'm not too familiar with ceph or Manila.

I haven't yet figured out if there's a way to use ceph-csi to attach a previously created (i.e., with Manila) ceph share, although that doesn't seem to be the k8s way of doing things anyway. Indeed, when using cinder-csi, we don't create the Volumes "manually" and then ask k8s to attach them to Pods.

Instead the intention is to create a ceph storage class and communicate with the ceph cluster (?) directly, i.e circumventing Manila, and create shares when, for example, a PV with the ceph storage class is created.

I would love to hear if there are any thoughts on this, or if I'm missing the mark altogether, that's preferred, actually!

-- a.v.e

**Comment by zonca** [comment]
@ana-v-espinoza I think we can look into `ceph-csi` later on, when we switch to the newer Kubernetes provided by Openstack Magnum via Cluster API. At that point I'll create a new tutorial about using Manila through `ceph-csi`.

For the time being, I suggest you do what takes less effort:

1) If using a custom minimal image with NFS support is easier, which I guess it is, you can keep doing that for the time being.

2) Otherwise, if you find more convenient and possibly more reliable to use the Jetstream-provided minimal image + Manila, then you can switch to using Ceph volumes as in https://www.zonca.dev/posts/2022-12-05-jetstream2-kubernetes-manila.html.

**Comment by ana-v-espinoza** [comment]
I think we will continue to use the first option for the time being until we've had the opportunity to experiment a bit with Magnum.

If y'all need help with developing or testing something, please reach out. I'm always more than happy to help.
