### ISSUE TITLE
ansible-core 2.12 does not support Python 3.12

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#86]
When running ansible, I am seeing:

```
    "msg": "Status code was -1 and not [200]: An unknown error occurred: 'CustomHTTPSConnection' object has no attribute 'cert_file'",
```

The root issue seems to be described [here](https://forum.ansible.com/t/error-saying-customhttpsconnection-object-has-no-attribute-cert-file/7390). 

"ansible-core 2.12 is EOL, and does not support Python 3.12"

Python 3.12 is coming from the new minimal JS2 VMs.

cc: @ana-v-espinoza

**Comment by zonca** [comment]
@julienchastang there are 3 minimal JS2 images, I guess you are using `Featured-Minimal-Ubuntu24`

please use `Featured-Minimal-Ubuntu22`, that has Python 3.10 and should support Ansible without issues.

**Comment by zonca** [comment]
@julienchastang have you solved this?

**Comment by julienchastang** [comment]
Thanks @zonca. At some point and as a stopgap, I snapshot my own image and have been going with that. I have not had a chance to check out this latest suggestion, but it does make sense.

**Comment by julienchastang** [comment]
Just a follow up that I was able to confirm that using the `Featured-Minimal-Ubuntu22` image solves this problem. Thanks again.
