### ISSUE TITLE
Update Dask Tutorial.

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#87]
Hi Andrea,

I am currently troubleshooting an issue with the Dask Gateway API. While accessing the API through Traefik works (e.g., http://traefik-dask-gateway/services/dask-gateway/api/health returns a `200` OK response), access via the service IP returns `404` Not Found errors for all tested endpoints.

I don't know if I am doing something wrong or the tutorial may need an update.

Thanks.

**Comment by zonca** [comment]
@julienchastang sure, how urgent is it? Do you have a tutorial/class starting soon?

**Comment by julienchastang** [comment]
Thanks for the quick response. My colleague at U Wisc is doing a class using Dask on December 6. However, I'd like to have some margin of error given the difficulties I've had with Dask in the past an also the forthcoming holidays. Again, thank you very much for this.

**Comment by julienchastang** [comment]
I keep seeing errors like those below. The cluster appears to try to start, but then seems to immediately die. Those logs are from the `api-dask-gateway-` pod.


```
[W 2024-11-13 20:46:19.921 DaskGateway] 401 GET /api/v1/clusters/jhub.97e91ffd8162479e9faf6b5a704685d7?wait 0.368ms
[I 2024-11-13 20:46:23.119 DaskGateway] 200 GET /api/v1/clusters/jhub.97e91ffd8162479e9faf6b5a704685d7?wait 3196.878ms
[I 2024-11-13 20:46:23.122 DaskGateway] 204 DELETE /api/v1/clusters/jhub.97e91ffd8162479e9faf6b5a704685d7 0.254ms
```

**Comment by julienchastang** [comment]
Actually, the problem may have been on my end all along, but I won't have a chance to test until tomorrow (so don't work on this). As an aside, `kubectl` can be kind of terrible about giving you good diagnostics. Logging into the node and getting information from `crictl` can be much better in some situation. I definitely learned some stuff today :-)

**Comment by julienchastang** [comment]
Like I said, the problem was ultimately on my side. I messed up when building the `dask-gateway` image. However, diagnosing the issue was made more difficult because `kubectl` was not reporting errors. The dask worker pod was immediately dying and there was no diagnostic info there anyway. I ended up sshing into the Kubernetes worker node and issuing a `crictl ps -a` to find the problematic container. You have about 30 seconds to do a `crictl inspect <id>` before the exited container is cleaned up. Therein I as able to find a pointer to a log file that indicated `dask-gateway` was not found (error not reported back to `kubectl`) and that is how I figured I had built the wrong container. Anyway, you can add this methodology to our debugging and troubleshooting arsenal.

About the update to the tutorial, there has been one update to dask since the tutorial. I will leave it up to you. Feel free to close this issue if you wish since the tutorial still is valid.

**Comment by zonca** [comment]
@julienchastang did you try using `kubectl logs --previous`?

**Comment by julienchastang** [comment]
Yes, and it did not work. I don't have the message, but it was something like not found. Indeed, even the exited container is quickly removed when looking at `crictl ps -a`. I tried various options to have the pod remain after error for post-mortem analysis, but nothing worked except what I described. Maybe I missed something.

**Comment by zonca** [comment]
@julienchastang thanks, added to the kubespray tutorial, it will be published next time I refresh the blog

**Comment by zonca** [comment]
Given Magnum is coming, I'll wait for that to update tutorials
