### ISSUE TITLE
helm init error

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#9]
With the new setup, when calling `helm init`, I am seeing:

```
Creating /home/ubuntu/.helm
Creating /home/ubuntu/.helm/repository
Creating /home/ubuntu/.helm/repository/cache
Creating /home/ubuntu/.helm/repository/local
Creating /home/ubuntu/.helm/plugins
Creating /home/ubuntu/.helm/starters
Creating /home/ubuntu/.helm/cache/archive
Creating /home/ubuntu/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /home/ubuntu/.helm.
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 127.0.0.1:8080: connect: connection refused
```

**Comment by zonca** [comment]
have you checked that you have the same version of `helm` for client and server? Is that missing from my tutorial? is that case can you add it?

**Comment by zonca** [comment]
use `helm version`

**Comment by zonca** [comment]
also is `kubectl` working fine on that machine?

**Comment by julienchastang** [comment]
For posterity's sake, I should have mentioned that I am referring to [the instructions here](https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray-jupyterhub.html).

`kubectl` is working from the client (via the ssh tunnel setup), but not on the master node. That is also where `helm init` is failing.

```
ubuntu@kube-exp-k8s-master-1:~$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused

ubuntu@kube-exp-k8s-master-1:~$ helm init
$HELM_HOME has been configured at /home/ubuntu/.helm.
Error: error installing: Post http://localhost:8080/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp 127.0.0.1:8080: connect: connection refused
```

```
ubuntu@kube-exp-k8s-master-1:~/jupyterhub-deploy-kubernetes-jetstream$ kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

From client:

```
[openstack@c65d2fec4d7f ~]$ kubectl get nodes
NAME                     STATUS   ROLES    AGE   VERSION
kube-exp-k8s-master-1    Ready    master   59m   v1.12.5
kube-exp-k8s-node-nf-1   Ready    node     57m   v1.12.5
```

I don't run helm on the client, just the master node. To be clear here, I am defining the client as being the host I am running terraform, ansible, etc. to build the kube cluster.

**Comment by zonca** [comment]
I wonder if the configuration is just for the `root` user, can you try to switch to root?

I prefer to run helm on the client, so that all my config files are safe if I need to tear down the master node. and helm is super easy to install on the client, once kubectl works already

**Comment by julienchastang** [comment]
OK, running entirely on the client, both `helm` and `kubectl`, seems to work. Closing for now.
